server:
  port: 8080

spring:
  application:
    name: NaChimBal
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nachimbaldb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root # 본인의 MySQL 비밀번호
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true # SQL을 예쁘게 출력해줌.
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    # 본인의 프로젝트 패키지 경로에 맞춰 수정
    com.axis.nachimbal: DEBUG


# tmap api
api:
  key: ILzQCLjYOD4LLtSLW6pp76kmDw7LLa1z7quPigcd
  base-url: https://apis.openapi.sk.com/tmap

# ncp maps api (reverse geocoding)
ncp:
  maps:
    client-id: "r68al6x3jb"
    client-secret: "U5v0qkK9VC9mikeHicaCQPtaRYhxMLajWYBlsbT6"
    reverse-geocode-url: https://maps.apigw.ntruss.com/map-reversegeocode/v2/gc

# 임시: 인증 미구현 단계 - 하드코딩할 사용자 ID
app:
  temp:
    default-user-id: 1

# AI 서버 주소 (로컬)
ai:
  server:
    url: http://localhost:8000